/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void test_getquote_specific_quote() {
        System.out.println(System.getProperty("user.dir"));
        File recentQuotesJSONFile = new File("./src/test/resources/recentquotes.json");
        Quote[] array = App.getQuotesArray(recentQuotesJSONFile);
        assert(App.getQuote(array, 1).equals("Ask no questions, and you'll be told no lies.\n" +
                "-- Charles Dickens"));
    }

}
