/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        File recentQuotesJSONFile = new File("./app/src/main/resources/recentquotes.json");
        Quote[] quotesArray = getQuotesArray(recentQuotesJSONFile);
        int randomIndex = getRandomAvailibleIndex(quotesArray.length);
        System.out.println(getQuote(quotesArray, randomIndex));
    }

    public static int getRandomAvailibleIndex(int arrayLength) {
        Random rand = new Random();
        return rand.nextInt(0, arrayLength); // upper bound is exclusive
    }

    public static Quote[] getQuotesArray(File quotesJSONFile) {
        Quote[] output = null;
        FileReader reader;
        Gson gson = new Gson();
        try {
            reader = new FileReader(quotesJSONFile);
            output = gson.fromJson(reader, Quote[].class);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return output;
    }

    public static String getQuote(Quote[] quotesArray, int index) {
        return quotesArray[index].text + "\n-- " + quotesArray[index].author;
    }

}
